parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
plugins: 
  - '@typescript-eslint'
extends: 
  # - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
env:
  node: true
  es6: true
  mocha: true
# rules:
#   indent: off
#   func-names: [2, never]
#   no-shadow: [2, { allow: [error, err, response, resolve, reject] }]
#   no-case-declarations: off
#   no-param-reassign: off
#   comma-dangle: off
#   radix: off
#   no-unused-vars: 1
#   consistent-return: off
#   no-prototype-builtins: off
#   no-await-in-loop: off
#   no-use-before-define: off
#   no-restricted-syntax: off
#   no-empty: off
#   no-continue: off
#   require-yield: off

rules:
  # indent: off
  '@typescript-eslint/indent': off
  # func-names: [error, never]
  # no-shadow: [error, { allow: [error, err, response, resolve, reject] }]
  # no-case-declarations: off
  # no-param-reassign: off
  # comma-dangle: off
  '@typescript-eslint/comma-dangle': off
  # radix: off
  # no-unused-vars: 1
  # consistent-return: off
  # no-prototype-builtins: off
  # no-await-in-loop: off
  # no-use-before-define: off
  # no-restricted-syntax: off
  # no-empty: off
  # no-continue: off
  # require-yield: off
  '@typescript-eslint/no-explicit-any': off
  'no-empty-function': off # Is this really required? (I adopted that from https://github.com/typescript-eslint/typescript-eslint/blob/v4.28.3/packages/eslint-plugin/docs/rules/no-empty-function.md#how-to-use-1)
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-this-alias': off
