parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
plugins: 
  - '@typescript-eslint'
extends: 
  - plugin:@typescript-eslint/recommended
  - prettier
env:
  node: true
  es6: true
  mocha: true
rules:
  '@typescript-eslint/indent': off
  '@typescript-eslint/comma-dangle': off
  '@typescript-eslint/no-explicit-any': off
  'no-empty-function': off # Is this really required? (I adopted that from https://github.com/typescript-eslint/typescript-eslint/blob/v4.28.3/packages/eslint-plugin/docs/rules/no-empty-function.md#how-to-use-1)
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-this-alias': off
