extends: 
  - eslint:recommended
  - prettier
env:
  node: true
  es6: true
  mocha: true
parserOptions:
  ecmaVersion: 2019
rules:
  indent: 0
  func-names: [2, never]
  no-shadow: [2, { allow: [error, err, response, resolve, reject] }]
  no-case-declarations: 0
  no-param-reassign: 0
  comma-dangle: 0
  radix: 0
  no-unused-vars: 1
  consistent-return: 0
  no-prototype-builtins: 0
  no-await-in-loop: 0
  no-use-before-define: 0
  no-restricted-syntax: 0
  no-empty: 0
  no-continue: 0
  require-yield: 0
