parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
plugins: 
  - '@typescript-eslint'
extends: 
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
env:
  node: true
  es6: true
  mocha: true
rules:
  '@typescript-eslint/indent': off
  '@typescript-eslint/comma-dangle': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-this-alias': off
  '@typescript-eslint/no-unused-vars': [off, varsIgnorePattern: ^_]
