name: CI - ts build check

on:
  pull_request:
    branches: [master]

jobs:
  ts_build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup

      - name: TypeScript test build
        run: pnpm run build-check
